# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('landmark_type', models.CharField(blank=True, max_length=30)),
                ('user_type', models.CharField(choices=[('Business', 'Business'), ('Student', 'Student'), ('Tourist', 'Tourist')], default='Business', max_length=8)),
                ('industry_type', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('unit_number', models.CharField(blank=True, max_length=3)),
                ('street_number', models.CharField(blank=True, max_length=3)),
                ('suburb', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('unit_number', models.CharField(blank=True, max_length=3)),
                ('street_number', models.CharField(blank=True, max_length=3)),
                ('suburb', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user_type', models.CharField(choices=[('Business', 'Business'), ('Student', 'Student'), ('Tourist', 'Tourist')], default='Business', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
