# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0002_auto_20170911_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Student', 'Student'), ('Tourist', 'Tourist')], default='Business', max_length=2),
        ),
    ]
