# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0004_auto_20170911_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_number',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suburb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_number',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
