# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0005_auto_20170915_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
