# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0006_auto_20171019_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
