# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0007_auto_20171019_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='landmark_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
