# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0007_auto_20171019_2008'),
        ('CityApp', '0006_cityinfo_slug'),
    ]

    operations = [
    ]
