# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0008_merge_20171021_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
