# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityApp', '0008_cityinfo_landmark_pic'),
        ('CityApp', '0010_remove_cityinfo_picture'),
    ]

    operations = [
    ]
